//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Converter.AlaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlaService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name from from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverter", ReplyAction="*")]
        Unit_Converter.AlaService.CurrencyConverterResponse CurrencyConverter(Unit_Converter.AlaService.CurrencyConverterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrencyConverter", ReplyAction="*")]
        System.Threading.Tasks.Task<Unit_Converter.AlaService.CurrencyConverterResponse> CurrencyConverterAsync(Unit_Converter.AlaService.CurrencyConverterRequest request);
        
        // CODEGEN: Generating message contract since element name from from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LengthConverter", ReplyAction="*")]
        Unit_Converter.AlaService.LengthConverterResponse LengthConverter(Unit_Converter.AlaService.LengthConverterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LengthConverter", ReplyAction="*")]
        System.Threading.Tasks.Task<Unit_Converter.AlaService.LengthConverterResponse> LengthConverterAsync(Unit_Converter.AlaService.LengthConverterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyConverterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyConverter", Namespace="http://tempuri.org/", Order=0)]
        public Unit_Converter.AlaService.CurrencyConverterRequestBody Body;
        
        public CurrencyConverterRequest() {
        }
        
        public CurrencyConverterRequest(Unit_Converter.AlaService.CurrencyConverterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrencyConverterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public CurrencyConverterRequestBody() {
        }
        
        public CurrencyConverterRequestBody(string from, string to, string value) {
            this.from = from;
            this.to = to;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyConverterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyConverterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Unit_Converter.AlaService.CurrencyConverterResponseBody Body;
        
        public CurrencyConverterResponse() {
        }
        
        public CurrencyConverterResponse(Unit_Converter.AlaService.CurrencyConverterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrencyConverterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrencyConverterResult;
        
        public CurrencyConverterResponseBody() {
        }
        
        public CurrencyConverterResponseBody(string CurrencyConverterResult) {
            this.CurrencyConverterResult = CurrencyConverterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LengthConverterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LengthConverter", Namespace="http://tempuri.org/", Order=0)]
        public Unit_Converter.AlaService.LengthConverterRequestBody Body;
        
        public LengthConverterRequest() {
        }
        
        public LengthConverterRequest(Unit_Converter.AlaService.LengthConverterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LengthConverterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public LengthConverterRequestBody() {
        }
        
        public LengthConverterRequestBody(string from, string to, string value) {
            this.from = from;
            this.to = to;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LengthConverterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LengthConverterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Unit_Converter.AlaService.LengthConverterResponseBody Body;
        
        public LengthConverterResponse() {
        }
        
        public LengthConverterResponse(Unit_Converter.AlaService.LengthConverterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LengthConverterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LengthConverterResult;
        
        public LengthConverterResponseBody() {
        }
        
        public LengthConverterResponseBody(string LengthConverterResult) {
            this.LengthConverterResult = LengthConverterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Unit_Converter.AlaService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Unit_Converter.AlaService.WebService1Soap>, Unit_Converter.AlaService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Unit_Converter.AlaService.CurrencyConverterResponse Unit_Converter.AlaService.WebService1Soap.CurrencyConverter(Unit_Converter.AlaService.CurrencyConverterRequest request) {
            return base.Channel.CurrencyConverter(request);
        }
        
        public string CurrencyConverter(string from, string to, string value) {
            Unit_Converter.AlaService.CurrencyConverterRequest inValue = new Unit_Converter.AlaService.CurrencyConverterRequest();
            inValue.Body = new Unit_Converter.AlaService.CurrencyConverterRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.value = value;
            Unit_Converter.AlaService.CurrencyConverterResponse retVal = ((Unit_Converter.AlaService.WebService1Soap)(this)).CurrencyConverter(inValue);
            return retVal.Body.CurrencyConverterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Unit_Converter.AlaService.CurrencyConverterResponse> Unit_Converter.AlaService.WebService1Soap.CurrencyConverterAsync(Unit_Converter.AlaService.CurrencyConverterRequest request) {
            return base.Channel.CurrencyConverterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Unit_Converter.AlaService.CurrencyConverterResponse> CurrencyConverterAsync(string from, string to, string value) {
            Unit_Converter.AlaService.CurrencyConverterRequest inValue = new Unit_Converter.AlaService.CurrencyConverterRequest();
            inValue.Body = new Unit_Converter.AlaService.CurrencyConverterRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.value = value;
            return ((Unit_Converter.AlaService.WebService1Soap)(this)).CurrencyConverterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Unit_Converter.AlaService.LengthConverterResponse Unit_Converter.AlaService.WebService1Soap.LengthConverter(Unit_Converter.AlaService.LengthConverterRequest request) {
            return base.Channel.LengthConverter(request);
        }
        
        public string LengthConverter(string from, string to, string value) {
            Unit_Converter.AlaService.LengthConverterRequest inValue = new Unit_Converter.AlaService.LengthConverterRequest();
            inValue.Body = new Unit_Converter.AlaService.LengthConverterRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.value = value;
            Unit_Converter.AlaService.LengthConverterResponse retVal = ((Unit_Converter.AlaService.WebService1Soap)(this)).LengthConverter(inValue);
            return retVal.Body.LengthConverterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Unit_Converter.AlaService.LengthConverterResponse> Unit_Converter.AlaService.WebService1Soap.LengthConverterAsync(Unit_Converter.AlaService.LengthConverterRequest request) {
            return base.Channel.LengthConverterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Unit_Converter.AlaService.LengthConverterResponse> LengthConverterAsync(string from, string to, string value) {
            Unit_Converter.AlaService.LengthConverterRequest inValue = new Unit_Converter.AlaService.LengthConverterRequest();
            inValue.Body = new Unit_Converter.AlaService.LengthConverterRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.value = value;
            return ((Unit_Converter.AlaService.WebService1Soap)(this)).LengthConverterAsync(inValue);
        }
    }
}
